services:
  postgres_db:
    image: postgres:alpine
    container_name: reading-list-db-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # In production, we usually don't mount local scripts unless necessary
      # - ./init-db:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  api:
    # CHANGED: No more 'build'. We use the image from Docker Hub.
    image: anusreedha143/book-management-api:latest
    container_name: books_management_api
    depends_on:
      postgres_db:
        condition: service_healthy
    # We still need the env file for DB credentials
    env_file: .env
    ports:
      - "4000:4000"
    networks:
      - app_network

  web:
    # CHANGED: We use the web image from Docker Hub.
    image: anusreedha/book-management-web:latest
    container_name: books_management_web_app
    depends_on:
      - api
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: