apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api
  namespace: book-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      imagePullSecrets:
      - name: stackit-registry-secret
      containers:
      - name: api
        image: registry.onstackit.cloud/book-inventory/go-web-api:2.0.0
        ports:
        - containerPort: 4000
        env:
        - name: READINGLIST_DB_DSN
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_URL
        - name: CORS_TRUSTED_ORIGINS
          value: "http://booksinventory.books.stackit.gg"
---
apiVersion: v1
kind: Service
metadata:
  name: book-api-service
  namespace: book-inventory
spec:
  selector:
    app: book-api
  ports:
  - port: 80
    targetPort: 4000
  type: ClusterIP
